# Плагин разработан пользователем форума rubukkit.org под ником Qmaks.
# Официальная тема плагина -> http://rubukkit.org/threads/fun-askme-zadaj-igrokam-parochku-voprosov-vse-versii.130026/
# Страница создателя на форуме (Все вопросы, просьбы, предложения в личку) -> http://rubukkit.org/members/qmaks.45892/

# Порядок задавания вопросов:
# 1 - рандомно (В неизвестном порядке).
# 2 - по порядку (От первого до последнего вопроса и так по кругу).
mode: 1
# Задержка перед задаванием следующего вопроса.
# Время до следующего вопроса после ответа на поставленный вопрос или сообщения о истечении времени, отведенного на ответ на заданный вопрос.
# Указывается в секундах.
# 60 секунд - 1 минута (Пасиба, Кэп).
gameDelay: 60
# Время, отведенное на ответ на заданный вопрос.
# Указывается в секундах, соответственно.
gamePeriod: 30
# Символ, который должен стоять вначале ответа или предложения и т.д.
# Т.е если вы что-то напишите туда, то для того, чтоб сообщение считалось "ответом" надо поставить вначале этот символ.
# Если же нам не нужна данная функция, то просто оставляем поле пустым.
# По дефолту вначале сообщения должна стоять стрелочка вправо (Т.е в чат надо будет отвечать так: >Ответ на вопрос).
# Если мы ее уберем (Смотреться будет так: answerPrefix: ""), то в чат надо будет отвечать так: Ответ на вопрос.
answerPrefix: ">"
# Выводимый в чат префикс плагина
# Placeholder: <pluginPrefix>
# Используется в нижеприведенных примерах вопросов.
pluginPrefix: "&f[&6AskMe&f]&r"
# То, что выводится в чат когда пробивает час умников и умниц.
# Тут так-же используется placeholder <questuion>, вместо него высвечивается вопрос.
question-msg:
    - "&c█▀▀▀▀▀▀▀▀█ &bВнимание, вопрос! &c█▀▀▀▀▀▀▀█"
    - "&c█▌"
    - "&c██▌ &6<question>"
    - "&c█▌"
    - "&c█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█"
# Список вопросов.
questions:
    # Номер вопроса
    1:
        # Вопрос
        # Placeholder - <question>
        question: "Чему равно число ПИ если его сократить до сотых?"
        # Все возможные ответы. Регистр не учитывается.
        answers: 
            - "3.14"
            - "3,14"
        # Команда, выполняемая от имени консоли в случае правильного ответа от игрока.
        # Placeholder <sender> - игрок, отправивший ответ.
        # В данном примере правильно ответившему игроку прибавляется 3000$ на баланс.
        reward-command: "eco give <sender> 3000"
        # Сообщение, выводимое при отправлении неверного ответа.
        # Placeholder <pluginPrefix> - префикс плагина.
        # Placeholder <sender> - игрок, отправивший ответ.
        wrong-answer: "<pluginPrefix> &cНеправильный ответ! <sender>, хорошенько подумай!"
        # Сообщение, выводимое при отправлении верного ответа.
        # Placeholder <pluginPrefix> - префикс плагина.
        # Placeholder <sender> - игрок, отправивший ответ.
        correct-answer: "<pluginPrefix> &a<sender>, великолепно! Учительница математики должна гордиться тобой :)"
        # Сообщение, выводимое в общий чат при истечении выделенного времени для ответа на вопрос.
        # Placeholder <pluginPrefix> - префикс плагина.
        no-reply-msg: "<pluginPrefix> &cИ где ваши математические знания, а?!"
        # Сообщение, выводимое при отправлении игроком верного ответа.
        # Placeholder <pluginPrefix> - префикс плагина.
        # Placeholder <sender> - игрок, отправивший ответ.
        massnotification: "<pluginPrefix> &6Игрок <sender> ответил верно и получил 3000$"
    2:
        question: "Какая гора считается самой высокой?"
        answers: 
            - "Эверест"
        reward-command: "give <sender> diamond_sword"
        wrong-answer: "<pluginPrefix> &cФу, глупенький ты какой-то :c"
        correct-answer: "<pluginPrefix> &a<sender>, ты несомненно умён! Ты правильно ответил и получишь за это приз :)"
        no-reply-msg: "<pluginPrefix> &aСила георграааафииии, приди!"
        massnotification: "<pluginPrefix> &6Игрок <sender> загуглил быстрее всех, поздравим его с этим! :D"